# Generated by Django 4.1.7 on 2023-03-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VillagerResponseDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('villager_option', models.TextField()),
                ('villager_why', models.TextField()),
            ],
        ),
    ]
